# Generated by Django 3.0.8 on 2020-07-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_memo_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
